<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%accessors}}".
 *
 * @property int $id
 * @property int|null $fk_user User ID
 * @property int|null $fk_request Request ID
 * @property string $name Name
 * @property string|null $email Email Address
 * @property string $role User Role Options
 * @property string|null $affiliation User Affiliation Options
 * @property string $date_created Date Created
 * @property string|null $date_modified Date Modified
 */
class DataAccessor extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%accessors}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fk_user', 'fk_request'], 'integer'],
            [['name', 'role', 'email'], 'required'],
            [['date_created', 'date_modified'], 'safe'],
            [['name'], 'string', 'max' => 60],
            [['email'], 'email'],
            [['email', 'role', 'affiliation'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fk_user' => 'User ID',
            'fk_request' => 'Request ID',
            'name' => 'Name',
            'email' => 'Email Address',
            'role' => 'User Role',
            'affiliation' => 'User Affiliation',
            'date_created' => 'Date Created',
            'date_modified' => 'Date Modified',
        ];
    }

    /**
     * Gets query for [[FkRequest]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFkRequest()
    {
        return $this->hasOne(Project::className(), ['id' => 'fk_request']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($insert){
            EmailMessage::sendMail('access', $this);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
